channels:
  - conda-forge
  - nodefaults
dependencies:
  # build
  - pip
  - flit >=3.9.0,<4.0.0
  - python-build
  # run
  - python >=3.9
  - jupyterlite-pyodide-kernel >=0.3.0,<0.4.0
  - jupyterlite-core >=0.3.0,<0.4.0
  - pyodide-lock ==0.1.0a4
  - tornado
  # selenium
  - selenium >=4.19.0,<5.0.0
  - geckodriver
  - firefox ==115.*
  # docs
  - sphinx
  - myst-parser
  - pydata-sphinx-theme
  # demo
  - jupyterlab >=4.1,<4.2
  - ipywidgets >=8.1,<8.2
  # lint
  - ruff >=0.3.0
  - pyproject-fmt
  # test
  - pytest >=8,<9
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-sugar
  - pytest-xdist
