version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libpangocairo-1.0-0
    - libx11-xcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxi6
    - libxtst6
    - libnss3
    - libcups2
    - libxss1
    - libxrandr2
    - libasound2
    - libatk1.0-0
    - libgtk-3-0
  tools:
    python: mambaforge-latest
  jobs:
    pre_build:
      - pixi install --environment=rtd
      - pixi run --environment=rtd build
      - pixi run --environment=rtd docs-lite
      - pixi run --environment=rtd readthedocs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
conda:
  environment: docs/environment.yml
