version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - firefox
  tools:
    python: mambaforge-latest
  jobs:
    pre_build:
      - pixi install --environment=docs
      - pixi run --environment=docs build
      - pixi run --environment=docs docs-lite
      - pixi run --environment=docs readthedocs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
conda:
  environment: docs/environment.yml
