name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1
  JLPL_TIMEOUT: 300
  JLPL_PIXI_VERSION: &pixi_version v0.61.0
  _JLPL_VM_LINUX_MIN: &vm_linux_min ubuntu-22.04
  _JLPL_VM_WIN: &vm_win windows-2025
  _JLPL_VM_WIN_MIN: &vm_win_min ubuntu-22.04
  _JLPL_VM_OSX: &vm_osx macos-15
  _JLPL_VM_OSX_MIN: &vm_osx_min macos-15-intel

jobs:
  build-pypi:
    runs-on: &vm_linux ubuntu-24.04
    steps:
      - uses: &uses_checkout actions/checkout@v6
      - uses: &uses_setup_pixi prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: *pixi_version
          cache: true
          environments: build
      - run: pixi run build-pypi
      - run: |-
          mkdir -p build && \
          echo ${{ github.run_number }} > .pixi/task-cache-v0/.skip-pypi-dist
      - uses: &uses_upload actions/upload-artifact@v6
        with: &with_pypi
          name: jlpl-${{ github.run_number }}-dist-pypi
          path: dist
      - uses: *uses_upload
        with: &with_build
          name: jlpl-${{ github.run_number }}-build
          path: .pixi/task-cache-v0

  build-conda:
    runs-on: *vm_linux
    needs: [build-pypi]
    steps:
      - uses: *uses_checkout
      - uses: *uses_setup_pixi
        with: { pixi-version: *pixi_version, cache: true, environments: rattler }
      - &step_download_pypi
        uses: &uses_download actions/download-artifact@v6
        with: *with_pypi
      - run: pixi run build-rattler
      - uses: *uses_upload
        with: &with_dist_conda
          name: jlpl-${{ github.run_number }}-dist-conda
          path: dist

  lint:
    runs-on: *vm_linux
    steps:
      - uses: *uses_checkout
      - uses: *uses_setup_pixi
        with: { pixi-version: *pixi_version, cache: true, environments: lint }
      - run: pixi run lint

  test:
    name: |-
      test ${{ matrix.pkg }} ${{ matrix.os }} ${{ matrix.test-env }} (${{ matrix.browser }})
    needs: [build-pypi]
    runs-on: ${{ matrix.vm }}
    strategy:
      fail-fast: false
      matrix:
        test-env: [min, max]
        os: [linux, osx, win]
        pkg: [core, uv, wd]
        exclude:
          - { test-env: min, pkg: uv }
        include:
          # see https://github.com/actions/runner-images#available-images
          - { test-env: max, os: osx, vm: *vm_osx, browser: chrome }
          - { test-env: max, os: linux, vm: *vm_linux, browser: chromium }
          - { test-env: max, os: linux, vm: *vm_linux, browser: firefox }
          - { test-env: max, os: win, vm: *vm_win, browser: chrome }
          - { test-env: min, os: osx, vm: *vm_osx_min, browser: chrome }
          - { test-env: min, os: linux, vm: *vm_linux_min, browser: firefox }
          - { test-env: min, os: win, vm: *vm_win_min, browser: firefox }
          - { test-env: uv-min, os: linux, vm: *vm_linux_min, pkg: uv }
          - { test-env: uv-min, os: win, vm: *vm_win_min, pkg: uv }
          - { test-env: uv-min, os: osx, vm: *vm_osx_min, pkg: uv }
    env:
      JLPL_BROWSER: ${{ matrix.browser }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: *uses_checkout
      - uses: *uses_setup_pixi
        with:
          pixi-version: *pixi_version
          cache: true
          environments: build test-${{ matrix.test-env }}
      - *step_download_pypi
      - &step_download_build
        uses: *uses_download
        with: *with_build
      - run: pixi run -v test-${{ matrix.test-env }}-pip
      - run: pixi run test-${{ matrix.test-env }}-cli
      - if: always()
        run: pixi run test-${{ matrix.test-env }}-${{ matrix.pkg }}
      - if: always()
        uses: *uses_upload
        with:
          name: |-
            jlpl-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.test-env }}-${{ matrix.pkg }}
          path: |
            .pixi/task-cache-v0
            build/reports

  docs:
    name: docs
    needs: [build-pypi, build-conda]
    runs-on: ubuntu-latest
    steps:
      - uses: *uses_checkout
      - uses: *uses_setup_pixi
        with: { pixi-version: *pixi_version, cache: true, environments: build docs }
      - *step_download_pypi
      - uses: *uses_download
        with: *with_dist_conda
      - *step_download_build
      - run: pixi run docs-lite
      - run: pixi run docs-sphinx
      - uses: *uses_upload
        with:
          name: jlpl-${{ github.run_number }}-docs
          path: build/docs
      - run: pixi run check
